### ISSUE TITLE
nested thrust calls does not return correct results 

### ISSUE THREAD

**Issue by ShawnLe** [thrust/thrust#882]
I have tested this snippet and try to explain its cause as well as a way to resolve it, but have failed to do so

```
#include <thrust/inner_product.h>
#include <thrust/functional.h>
#include <thrust/device_vector.h>
#include <thrust/random.h>

#include <thrust/execution_policy.h>

#include <iostream>
#include <cmath>
#include <boost/concept_check.hpp>

struct alter_tuple {

    alter_tuple(const int& a_, const int& b_) : a(a_), b(b_){};

    __host__ __device__
    thrust::tuple<int,int> operator()(thrust::tuple<int,int> X)
    {
    int Xx = thrust::get<0>(X);
    int Xy = thrust::get<1>(X);
    int Xpx = a*Xx-b*Xy;
    int Xpy = -b*Xx+a*Xy;

    printf("in (%d,%d) -> (%d,%d)\n",Xx,Xy,Xpx,Xpy);

        return thrust::make_tuple(Xpx,Xpy);
    }

    int a;   // these variables a,b are shared between different threads used by this functor kernel
    int b;   // which easily creates racing problem
};


struct alter_tuple_arr {

    alter_tuple_arr(int* a_, int* b_, int* c_, int* d_) : a(a_), b(b_), c(c_), d(d_) {};

    __host__ __device__
    thrust::tuple<int,int> operator()(const int& idx)
    {
    int Xx = a[idx];
    int Xy = b[idx]; 
    int Xpx = a[idx]*Xx-b[idx]*Xy;
    int Xpy = -b[idx]*Xx+a[idx]*Xy;

    printf("in (%d,%d) -> (%d,%d)\n",Xx,Xy,Xpx,Xpy);

        return thrust::make_tuple(Xpx,Xpy);
    }

    int* a;
    int* b;
    int* c;
    int* d;
};


struct bFuntor 
{
    bFuntor(int* av__, int* bv__, int* cv__, int* dv__, const int& N__) : av_(av__), bv_(bv__), cv_(cv__), dv_(dv__), N_(N__) {};

    __host__ __device__
    int operator()(const int& idx)
    {
    thrust::device_ptr<int> av_dpt = thrust::device_pointer_cast(av_);
    thrust::device_ptr<int> av_dpt1 = thrust::device_pointer_cast(av_+N_);
    thrust::device_ptr<int> bv_dpt = thrust::device_pointer_cast(bv_);
    thrust::device_ptr<int> bv_dpt1 = thrust::device_pointer_cast(bv_+N_);
    thrust::device_ptr<int> cv_dpt = thrust::device_pointer_cast(cv_);
    thrust::device_ptr<int> cv_dpt1 = thrust::device_pointer_cast(cv_+N_);
    thrust::device_ptr<int> dv_dpt = thrust::device_pointer_cast(dv_);
    thrust::device_ptr<int> dv_dpt1 = thrust::device_pointer_cast(dv_+N_);

    thrust::detail::normal_iterator<thrust::device_ptr<int>> a0 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(av_dpt);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> a1 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(av_dpt1);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> b0 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(bv_dpt);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> b1 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(bv_dpt1);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> c0 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(cv_dpt);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> c1 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(cv_dpt1);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> d0 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(dv_dpt);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> d1 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(dv_dpt1);

    // ** alter_tuple is WRONG
#define WRONG
#ifdef WRONG
    thrust::transform(thrust::device,
              thrust::make_zip_iterator(thrust::make_tuple(a0,b0)),
              thrust::make_zip_iterator(thrust::make_tuple(a1,b1)),
//            thrust::make_zip_iterator(thrust::make_tuple(cv_dpt,dv_dpt)),   // cv_dpt  
              thrust::make_zip_iterator(thrust::make_tuple(c0,d0)),   // cv_dpt  
              alter_tuple(cv_[idx],dv_[idx]));    
#endif

#ifdef RIGHT
    // ** alter_tuple_arr is CORRECT way to do it
    thrust::transform(thrust::device,
              thrust::counting_iterator<int>(0),
              thrust::counting_iterator<int>(N_),
//            thrust::make_zip_iterator(thrust::make_tuple(cv_dpt,dv_dpt)),   // cv_dpt  
              thrust::make_zip_iterator(thrust::make_tuple(c0,d0)),   // cv_dpt  
              alter_tuple_arr(av_,bv_,cv_,dv_));    
#endif

    for (int i=0; i<N_; i++)
      printf("out: (%d,%d) -> (%d,%d)\n",av_[i],bv_[i],cv_[i],dv_[i]);

        return cv_dpt[idx];
    }

    int* av_;
    int* bv_;
    int* cv_;
    int* dv_;
    int N_;
    float af;   // are these variables host side or device side??
};


__host__ __device__
unsigned int hash(unsigned int a)
{
    a = (a+0x7ed55d16) + (a<<12);
    a = (a^0xc761c23c) ^ (a>>19);
    a = (a+0x165667b1) + (a<<5);
    a = (a+0xd3a2646c) ^ (a<<9);
    a = (a+0xfd7046c5) + (a<<3);
    a = (a^0xb55a4f09) ^ (a>>16);
    return a;
}


int main(void)
{
      int N = 10;
      std::vector<int> av,bv,cv,dv;
      unsigned int seed = hash(10);
      thrust::default_random_engine rng(seed);
      thrust::uniform_real_distribution<float> u01(0,10);

      for (int i=0;i<N;i++) {
    av.push_back((int)u01(rng));
    bv.push_back((int)u01(rng));
    cv.push_back((int)u01(rng));
    dv.push_back((int)u01(rng));

//  printf("%d %d %d %d \n",av[i],bv[i],cv[i],dv[i]);
      }

      thrust::device_vector<int> av_d(N);
      thrust::device_vector<int> bv_d(N);
      thrust::device_vector<int> cv_d(N);
      thrust::device_vector<int> dv_d(N);
      av_d = av; bv_d = bv; cv_d = cv; dv_d = dv;

      thrust::transform(thrust::counting_iterator<int>(0),
            thrust::counting_iterator<int>(N),
            cv_d.begin(),
            bFuntor(thrust::raw_pointer_cast(av_d.data()), 
                  thrust::raw_pointer_cast(bv_d.data()),
                  thrust::raw_pointer_cast(cv_d.data()),
                  thrust::raw_pointer_cast(dv_d.data()),
                  N));    

      thrust::host_vector<int> bv_h(N);
      thrust::copy(bv_d.begin(), bv_d.end(), bv_h.begin());   // probably I forgot this! to copy back the result from device to host!

      return 0;
}
```
In this nested thrust calls, two nested functors were tested, one of them worked (one with "#define RIGHT"). In the case of WRONG functor i.e. alter_tuple:

Inside, the alter_tuple functor, I tried to print out the result (int printf("in...")) and this is correct calculation. However, when this result is returned to caller functor and is printed out (in printf("out....")), they are incorrect and are different with its previous calculation

how come can these results are different?  I printed them from the same variables

this difference is shown in output [here](https://pastebin.com/FSypmfs2)

**Comment by jaredhoberock** [comment]
Hi Shawn,
Is there a way to demonstrate the same problem in a simplified program? The complexity of the program makes it difficult to understand what this program is expected to do.

**Comment by ShawnLe** [comment]
Hi Jared, 

I have updated the code so that it files only the error case. I think I cannot simplify more the code because the error appears when thrust is called in nested manner i.e. main --> bFuntor --> alter_tuple. 

Instead, if the call is made directly i.e. main --> alter_tuple, the results are correct.

Again, in this case, the output is [here](https://pastebin.com/LL2rg67t) 

```
#include <thrust/inner_product.h>
#include <thrust/functional.h>
#include <thrust/device_vector.h>
#include <thrust/random.h>

#include <thrust/execution_policy.h>

#include <iostream>
#include <cmath>
#include <boost/concept_check.hpp>

struct alter_tuple {

    alter_tuple(const int& a_, const int& b_) : a(a_), b(b_){};

    __host__ __device__
    thrust::tuple<int,int> operator()(thrust::tuple<int,int> X)
    {
    int Xx = thrust::get<0>(X);
    int Xy = thrust::get<1>(X);
    int Xpx = a*Xx-b*Xy;
    int Xpy = -b*Xx+a*Xy;

    printf("in (%d,%d) -> (%d,%d)\n",Xx,Xy,Xpx,Xpy);

        return thrust::make_tuple(Xpx,Xpy);
    }

    int a;   // these variables a,b are shared between different threads used by this functor kernel
    int b;   // which easily creates racing problem?
};


struct bFuntor 
{
    bFuntor(int* av__, int* bv__, int* cv__, int* dv__, const int& N__) : av_(av__), bv_(bv__), cv_(cv__), dv_(dv__), N_(N__) {};

    __host__ __device__
    int operator()(const int& idx)
    {
    thrust::device_ptr<int> av_dpt = thrust::device_pointer_cast(av_);
    thrust::device_ptr<int> av_dpt1 = thrust::device_pointer_cast(av_+N_);
    thrust::device_ptr<int> bv_dpt = thrust::device_pointer_cast(bv_);
    thrust::device_ptr<int> bv_dpt1 = thrust::device_pointer_cast(bv_+N_);
    thrust::device_ptr<int> cv_dpt = thrust::device_pointer_cast(cv_);
    thrust::device_ptr<int> cv_dpt1 = thrust::device_pointer_cast(cv_+N_);
    thrust::device_ptr<int> dv_dpt = thrust::device_pointer_cast(dv_);
    thrust::device_ptr<int> dv_dpt1 = thrust::device_pointer_cast(dv_+N_);

    thrust::detail::normal_iterator<thrust::device_ptr<int>> a0 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(av_dpt);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> a1 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(av_dpt1);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> b0 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(bv_dpt);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> b1 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(bv_dpt1);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> c0 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(cv_dpt);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> c1 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(cv_dpt1);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> d0 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(dv_dpt);
    thrust::detail::normal_iterator<thrust::device_ptr<int>> d1 = thrust::detail::make_normal_iterator<thrust::device_ptr<int>>(dv_dpt1);

    // ** alter_tuple is WRONG
    thrust::transform(thrust::device,
              thrust::make_zip_iterator(thrust::make_tuple(a0,b0)),
              thrust::make_zip_iterator(thrust::make_tuple(a1,b1)),
              thrust::make_zip_iterator(thrust::make_tuple(c0,d0)),   // cv_dpt  
              alter_tuple(cv_[idx],dv_[idx]));    
    
    for (int i=0; i<N_; i++)
      printf("out: (%d,%d) -> (%d,%d)\n",av_[i],bv_[i],cv_[i],dv_[i]);

        return cv_dpt[idx];
    }

    int* av_;
    int* bv_;
    int* cv_;
    int* dv_;
    int N_;
    float af;   // are these variables host side or device side??
};


__host__ __device__
unsigned int hash(unsigned int a)
{
    a = (a+0x7ed55d16) + (a<<12);
    a = (a^0xc761c23c) ^ (a>>19);
    a = (a+0x165667b1) + (a<<5);
    a = (a+0xd3a2646c) ^ (a<<9);
    a = (a+0xfd7046c5) + (a<<3);
    a = (a^0xb55a4f09) ^ (a>>16);
    return a;
}


int main(void)
{
      int N = 10;
      std::vector<int> av,bv,cv,dv;
      unsigned int seed = hash(10);
      thrust::default_random_engine rng(seed);
      thrust::uniform_real_distribution<float> u01(0,10);

      for (int i=0;i<N;i++) {
	av.push_back((int)u01(rng));
	bv.push_back((int)u01(rng));
	cv.push_back((int)u01(rng));
	dv.push_back((int)u01(rng));

    //  printf("%d %d %d %d \n",av[i],bv[i],cv[i],dv[i]);
      }

      thrust::device_vector<int> av_d(N);
      thrust::device_vector<int> bv_d(N);
      thrust::device_vector<int> cv_d(N);
      thrust::device_vector<int> dv_d(N);
      av_d = av; bv_d = bv; cv_d = cv; dv_d = dv;

      thrust::transform(thrust::counting_iterator<int>(0),
            thrust::counting_iterator<int>(N),
            cv_d.begin(),
            bFuntor(thrust::raw_pointer_cast(av_d.data()), 
                  thrust::raw_pointer_cast(bv_d.data()),
                  thrust::raw_pointer_cast(cv_d.data()),
                  thrust::raw_pointer_cast(dv_d.data()),
                  N));    

      thrust::host_vector<int> bv_h(N);
      thrust::copy(bv_d.begin(), bv_d.end(), bv_h.begin());   

      return 0;
}
```

**Comment by ShawnLe** [comment]
Hi Jared,

I have tried to reduce the code to the minimum size. Yet, the error is still there. So, you might have a look at this code instead. 

I have identified the problem in a clearer way. In particular, it appears at this nested call to "transform" function
```
    // ** alter_tuple is WRONG
    thrust::transform(thrust::device,
              av_dpt,   
              av_dpt1,
              cv_dpt,   
              alter_tuple(bv_[idx]));   

```
and the cause is cv_dpt OutputIterator, it seems not to be able to retrieve correctly the returned values whereas the InputIterator av_dpt, av_dpt1 work just fine.
whole code is below
```
#include <thrust/inner_product.h>
#include <thrust/functional.h>
#include <thrust/device_vector.h>
#include <thrust/random.h>

#include <thrust/execution_policy.h>

#include <iostream>
#include <cmath>
#include <boost/concept_check.hpp>

struct alter_tuple {

    alter_tuple(const int& a_) : a(a_){};

    __host__ __device__
    int operator()(const int& X)
    {
    int Xp = a*X;

    printf("in %d*%d -> %d\n",X,a,Xp);

        return Xp;
    }

    int a;   
};


struct bFuntor 
{
    bFuntor(int* av__, int* bv__, int* cv__, const int& N__) : av_(av__), bv_(bv__), cv_(cv__), N_(N__) {};

    __host__ __device__
    int operator()(const int& idx)
    {
    thrust::device_ptr<int> av_dpt = thrust::device_pointer_cast(av_);
    thrust::device_ptr<int> av_dpt1 = thrust::device_pointer_cast(av_+N_);
    thrust::device_ptr<int> bv_dpt = thrust::device_pointer_cast(bv_);
    thrust::device_ptr<int> bv_dpt1 = thrust::device_pointer_cast(bv_+N_);
    thrust::device_ptr<int> cv_dpt = thrust::device_pointer_cast(cv_);
    thrust::device_ptr<int> cv_dpt1 = thrust::device_pointer_cast(cv_+N_);

    // ** alter_tuple is WRONG
    thrust::transform(thrust::device,
              av_dpt,   
              av_dpt1,
              cv_dpt,   
              alter_tuple(bv_[idx]));    
    
    for (int i=0; i<N_; i++)
      printf("out: %d*%d -> %d\n",av_[i],bv_[idx],cv_[i]);

        return cv_dpt[idx];
    }

    int* av_;
    int* bv_;
    int* cv_;
    int N_;
    float af;   
};


int main(void)
{
      int N = 4;
      std::vector<int> av = {0,1,3,5};
      std::vector<int> bv = {0,10,20,30};
      std::vector<int> cv = {-1,-2,2,3};

      thrust::device_vector<int> av_d(N);
      thrust::device_vector<int> bv_d(N);
      thrust::device_vector<int> cv_d(N);
      av_d = av; bv_d = bv; cv_d = cv; 
 
      // call with nested manner
      thrust::transform(thrust::counting_iterator<int>(0),
            thrust::counting_iterator<int>(N),
            cv_d.begin(),
            bFuntor(thrust::raw_pointer_cast(av_d.data()), 
                  thrust::raw_pointer_cast(bv_d.data()),
                  thrust::raw_pointer_cast(cv_d.data()),
                  N));    

      thrust::host_vector<int> bv_h(N);
      thrust::copy(bv_d.begin(), bv_d.end(), bv_h.begin());
      
      // call directly alter_tuple functor
      for (int idx = 0; idx < N; idx++) {
	thrust::transform(thrust::device,
			  av_d.begin(),
			  av_d.end(),
			  cv_d.begin(), 
			  alter_tuple(bv[idx]));    
	
	thrust::host_vector<int> ev_h(N);
	thrust::copy(cv_d.begin(), cv_d.end(), ev_h.begin());
	
	for (int i=0; i<N; i++)
	  printf("out direct: %d*%d -> %d\n",av[i],bv[idx],ev_h[i]);
      }

      return 0;
}
```
Again, here is the new output [link](https://pastebin.com/cJKR21si)

**Comment by jaredhoberock** [comment]
Hi Shawn,

Thanks for reducing the size of the problem. Unfortunately, I still don't understand what is the expected behavior of the program. I find it helpful to use `assert` to communicate assertions about program behavior. Do you think it could be used here?

**Comment by ShawnLe** [comment]
Hi Jared, 

I would like to close this issue. I have found the cause which is a data race when I write the test snippet. It is not a Thrust issue. Sorry for taking your time.
